packages:
  pip:
    install:
    - 'spacy'
  spacy:
    download:
    - 'en'
    #- 'en_core_web_sm'
    #- 'de_core_news_sm'
    #- 'fr_core_news_sm'
    #- 'es_core_news_sm'
    #- 'pt_core_news_sm'
    #- 'it_core_news_sm'
    #- 'nl_core_news_sm'
    #- 'el_core_news_sm'
    #- 'xx_ent_wiki_sm'

msg_broker:
  supported_mime:
  - 'text/plain'
  - 'text/richtext'

database:
  type: 'elasticsearch'
  connection:
  - name: 'elasticsearch'
    port: '9200'
    user: 'elasticuser'
    host: 'es'
    password: 'elasticpass'
    timeout: 2

api:
  blueprints_directory: 'blueprints'
